# Generated by Django 4.2.3 on 2023-07-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=250)),
                ('handel', models.CharField(max_length=100)),
                ('msrp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('salePrice', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
