# Generated by Django 4.2.3 on 2023-07-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='handel',
            new_name='handle',
        ),
    ]
