# Generated by Django 4.2.3 on 2023-07-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleApp', '0002_rename_handel_products_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='percentOnSale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
